### ISSUE TITLE
Documentation v1.0 ToDo List

### ISSUE THREAD

**Issue by stonier** [kobuki-base/kobuki_documentation#3]
**Goal**

User documentation in sphinx, code documentation in doxygen.

**New Documentation [WIP]**

* https://kobuki.readthedocs.io/en/devel/

**Resources**

Old documentation:

* http://yujinrobot.github.io/kobuki/enMainPage.html
* http://kobuki.yujinrobot.com/wiki/online-user-guide/

Looks like there is a nice read-the-docs version made by the Dabit lads:

* https://github.com/dabit-industries/kobuki_wiki
* https://iclebo-kobuki.readthedocs.io/en/latest

**Victory Conditions**

* [x] C++ API Documentation - Infra (doxygen) &rarr; https://github.com/kobuki-base/kobuki_core/commit/5e223307be88426a6dfc2e175499f69c349fce83
* [x] C++ API Documentation - Cleanup (remove what has been transferred to sphinx) &rarr; https://github.com/kobuki-base/kobuki_core/pull/29
* [x] User Documentation - Infra (sphinx) &rarr; [@github](https://github.com/kobuki-base/kobuki_documentation))
* [x] User Documentation - Publish on ReadTheDocs &rarr; [@readthedocs](https://kobuki.readthedocs.io/en/devel/)
* [x] User Documentation - Out of the Box &rarr; #9
* [x] User Documentation - Installing and Running the Software &rarr; #8
* [x] User Documentation - Creating Applications &rarr; https://github.com/kobuki-base/kobuki_core/pull/27, #14
* [x] User Documentation - Anatomy &rarr; #15
* [x] User Documentation - Specifications &rarr; #9
* [x] User Documentation - Conversions &rarr; #16
* [x] User Documentation - Protocol Specification &rarr; #16
* [x] User Documentation - Firmware
* [x] User Documentation - Media &rarr; #17
* [x] User Documentation - Docking &rarr; #19, punted software docs to #20
* [x] User Documentation - Embedded Board Development &rarr; #22
* [x] User Documentation - Hardware Extensions &rarr; #25
* [x] User Documentation - Troubleshooting the USB &rarr; eae2edbbe
* [x] User Documentation - Custom Driver Development &rarr; #26
* [x] User Documentation - ROS 1 &rarr; #9
* [x] User Documentation - Versioning &rarr; #24
* [x] User Documentation - C++ Api &rarr; #13
* [x] User Documentation - Glossary &rarr; #13
* [x] Continuous Integration - github workflow for C++ API on PR &rarr; https://github.com/kobuki-base/kobuki_core/commit/10c23f2abb968e747421341c7868be2084453092
* [x] Continuous Integration - github workflow for C++ API on push &rarr; https://github.com/kobuki-base/kobuki_core/commit/10c23f2abb968e747421341c7868be2084453092
* [x] Continuous Integration - PR Hook for ReadTheDocs jobs
* [x] Continuous Integration - github workflow for build_sources (nightly or weekly) &rarr; 8f0c931d, 85cef694
* [x] Github README - update kobuki_core, kobuki_ftdi, kobuki_firmware, kobuki_documentation
* [x] Github package.xml - update kobuki_core, kobuki_ftdi, kobuki_firmware, kobuki_documentation, kobuki_ros_interfaces, kobuki_resources, kobuki_ros
